name: Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: python manage.py test

  deploy:
    needs: test 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: 167.71.51.222
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          source /venv/bin/activate        
          cd /root/backbot/
          git pull origin master
          python manage.py migrate
          python manage.py collectstatic --noinput
          supervisorctl restart all
